name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          python-version: ${{ matrix["python-version"] }}

      - name: Install project dependencies
        run: |
          uv pip install pytest
          uv pip install -e .

      - name: Ruff format check
        run: uvx ruff format --check .

      - name: Ruff lint
        run: uvx ruff check .

      - name: Mypy
        run: uvx mypy .

      - name: Pytest
        run: uv run pytest -q

      - name: Build package
        run: uv build
